const TOOL_STATES = {
  DISABLE: 0,
  ENABLE: 1,
  PASSIVE: 2,
  ACTIVE: 3,
} as const;

const BUTTON_TYPES = {
  NONE: -1,
  LEFT: 0,
  MIDDLE: 1,
  RIGHT: 2,
} as const;

const EVENT_TYPES = {
  MOUSEMOVE: 'TX_MOUSEMOVE',
  TOUCHDOWN: 'TX_TOUCHDOWN',
  TOUCHUP: 'TX_TOUCHUP',
  TAP: 'TX_TAP',
  TOUCHMOVE: 'TX_TOUCHMOVE',
  RENDERED: 'TX_RENDERED',
} as const;

const EVENT_LEVELS = {
  [EVENT_TYPES.MOUSEMOVE]: TOOL_STATES.ENABLE,
  [EVENT_TYPES.TOUCHDOWN]: TOOL_STATES.ACTIVE,
  [EVENT_TYPES.TOUCHUP]: TOOL_STATES.ACTIVE,
  [EVENT_TYPES.TAP]: TOOL_STATES.ACTIVE,
  [EVENT_TYPES.TOUCHMOVE]: TOOL_STATES.ACTIVE,
  [EVENT_TYPES.RENDERED]: TOOL_STATES.ENABLE,
} as const;

export { EVENT_TYPES, EVENT_LEVELS, TOOL_STATES, BUTTON_TYPES };
