const EVENT_TYPES = {
  MOUSEMOVE: 'TX_MOUSEMOVE',
  TOUCHDOWN: 'TX_TOUCHDOWN',
  TOUCHUP: 'TX_TOUCHUP',
  TAP: 'TX_TAP',
  TOUCHMOVE: 'TX_TOUCHMOVE',
  RENDERED: 'TX_RENDERED',
};

export { EVENT_TYPES };
