const EVENT_TYPES = {
  MOUSEMOVE: 'TX_MOUSEMOVE',
  TOUCHDOWN: 'TX_TOUCHDOWN',
  TOUCHUP: 'TX_TOUCHUP',
  TAP: 'TX_TAP',
  TOUCHMOVE: 'TX_TOUCHMOVE',
  RENDERED: 'TX_RENDERED',
};

const EVENT_LEVELS = {
  [EVENT_TYPES.MOUSEMOVE]: 1,
  [EVENT_TYPES.TOUCHDOWN]: 2,
  [EVENT_TYPES.TOUCHUP]: 2,
  [EVENT_TYPES.TAP]: 2,
  [EVENT_TYPES.TOUCHMOVE]: 2,
  [EVENT_TYPES.RENDERED]: 1,
};

const VIEWPORT_EVENT_TYPES = {
  DICOM_INFO_CHANGE: 'DICOM_INFO_CHANGE',
  DISPLAY_STATE_CHANGE: 'DISPLAY_STATE_CHANGE',
  SERIES_INFO_CHANGE: 'SERIES_INFO_CHANGE',
};

export { EVENT_TYPES, EVENT_LEVELS, VIEWPORT_EVENT_TYPES };
